services:
  - type: web
    name: mongodb-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: mongodb